version: '3.4'

services:
  frontend:
    build:
      context: .
      target: final
      args:
        - VUE_APP_API_BASE=http://localhost:5001/api/
    ports:
      - "5000:80"
    restart: unless-stopped
    depends_on:
      - api
  api:
    image: ghcr.io/trenz-gmbh/meilidown:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - Meilisearch__Url=http://meilisearch:7700
      - Meilisearch__ApiKey=${MEILISEARCH_API_KEY:-masterKey}
    ports:
      - "5001:80"
    restart: unless-stopped
    depends_on:
      - meilisearch
    volumes:
      - ./appsettings.local.json:/app/appsettings.local.json
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
    restart: unless-stopped
    volumes:
      - meili_data:/data

volumes:
  meili_data:
